/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "fdojwzawzmyqkazwrshf"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkb2p3emF3em15cWthendyc2hmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE1NDE4NzIsImV4cCI6MjA5NzExNzg3Mn0.oJ2NQ-8dEgwroH-rcvI33m8rL7Tpp75f__LCPRUTbd4"